-- DB 생성   
DROP DATABASE IF EXISTS pizzaitho;
                                                                                                                                                                                                                     
  CREATE DATABASE IF NOT EXISTS pizzaitho                                                                                                                                                                                          
    DEFAULT CHARACTER SET utf8mb4                                                                                                                                                                                                   
    COLLATE utf8mb4_general_ci;                                                                                                                                                                                                     
  USE pizzaitho;                                                                                                                                                                                                                   
                                                                                                                                                                                                                                    
  -- USER                                                                                                                                                                                                                           
  CREATE TABLE `USER` (                                                                                                                                                                                                             
    user_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                         
    id VARCHAR(50) NOT NULL UNIQUE,                                                                                                                                                                                                 
    pw VARCHAR(255) NOT NULL,                                                                                                                                                                                                       
    name VARCHAR(50) NOT NULL,                                                                                                                                                                                                      
    stamp INT NOT NULL DEFAULT 0                                                                                                                                                                                                    
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- PRODUCT                                                                                                                                                                                                                        
  CREATE TABLE PRODUCT (                                                                                                                                                                                                            
    product_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                      
    name VARCHAR(100) NOT NULL,                                                                                                                                                                                                     
    description TEXT,                                                                                                                                                                                                               
    image VARCHAR(255),                                                                                                                                                                                                             
    base_price INT NOT NULL                                                                                                                                                                                                         
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- TOPPING                                                                                                                                                                                                                        
  CREATE TABLE TOPPING (                                                                                                                                                                                                            
    topping_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                      
    name VARCHAR(100) NOT NULL,                                                                                                                                                                                                     
    image VARCHAR(255),                                                                                                                                                                                                             
    price INT NOT NULL                                                                                                                                                                                                              
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
																																																								
  -- DOUGH                                                                                                                                                                                                                          
  CREATE TABLE DOUGH (                                                                                                                                                                                                              
    dough_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                        
    name VARCHAR(100) NOT NULL,                                                                                                                                                                                                     
    image VARCHAR(255),                                                                                                                                                                                                             
    extra_price INT NOT NULL                                                                                                                                                                                                        
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- CRUST                                                                                                                                                                                                                          
  CREATE TABLE CRUST (                                                                                                                                                                                                              
    crust_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                        
    name VARCHAR(100) NOT NULL,                                                                                                                                                                                                     
    image VARCHAR(255),                                                                                                                                                                                                             
    extra_price INT NOT NULL                                                                                                                                                                                                        
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- PRODUCT_DEFAULT_TOPPING
  CREATE TABLE PRODUCT_DEFAULT_TOPPING (                                                                                                                                                                                            
    product_id INT NOT NULL,                                                                                                                                                                                                        
    topping_id INT NOT NULL,                                                                                                                                                                                                        
    PRIMARY KEY (product_id, topping_id),                                                                                                                                                                                           
    CONSTRAINT fk_pdt_product                                                                                                                                                                                                       
      FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id),                                                                                                                                                                      
    CONSTRAINT fk_pdt_topping                                                                                                                                                                                                       
      FOREIGN KEY (topping_id) REFERENCES TOPPING(topping_id)                                                                                                                                                                       
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- ORDERS                                                                                                                                                                                                                         
  CREATE TABLE ORDERS (                                                                                                                                                                                                             
    order_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                        
    user_id INT NOT NULL,                                                                                                                                                                                                           
    order_table VARCHAR(100),                                                                                                                                                                                                       
    status VARCHAR(20) NOT NULL,                                                                                                                                                                                                    
    fcm_token VARCHAR(255),                                                                                                                                                                                                         
    order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                                                                                                                                                                                 
    CONSTRAINT fk_orders_user                                                                                                                                                                                                       
      FOREIGN KEY (user_id) REFERENCES `USER`(user_id)                                                                                                                                                                              
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- ORDER_DETAIL                                                                                                                                                                                                                   
  CREATE TABLE ORDER_DETAIL (                                                                                                                                                                                                       
    order_detail_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                 
    order_id INT NOT NULL,                                                                                                                                                                                                          
    product_id INT NOT NULL,
    dough_id INT NOT NULL,                                                                                                                                                                                                          
    crust_id INT,                                                                                                                                                                                                                   
    quantity INT NOT NULL DEFAULT 1,                                                                                                                                                                                                
    unit_price INT NOT NULL,                                                                                                                                                                                                        
    CONSTRAINT fk_od_order                                                                                                                                                                                                          
      FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),                                                                                                                                                                           
    CONSTRAINT fk_od_product                                                                                                                                                                                                        
      FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id),                                                                                                                                                                      
    CONSTRAINT fk_od_dough                                                                                                                                                                                                          
      FOREIGN KEY (dough_id) REFERENCES DOUGH(dough_id),                                                                                                                                                                            
    CONSTRAINT fk_od_crust                                                                                                                                                                                                          
      FOREIGN KEY (crust_id) REFERENCES CRUST(crust_id)                                                                                                                                                                             
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- ORDER_DETAIL_TOPPING                                                                                                                                                                                                           
  CREATE TABLE ORDER_DETAIL_TOPPING (                                                                                                                                                                                               
    order_detail_id INT NOT NULL,                                                                                                                                                                                                   
    topping_id INT NOT NULL,                                                                                                                                                                                                        
    quantity INT NOT NULL DEFAULT 1,                                                                                                                                                                                                
    PRIMARY KEY (order_detail_id, topping_id),                                                                                                                                                                                      
    CONSTRAINT fk_odt_order_detail                                                                                                                                                                                                  
      FOREIGN KEY (order_detail_id) REFERENCES ORDER_DETAIL(order_detail_id),                                                                                                                                                       
    CONSTRAINT fk_odt_topping                                                                                                                                                                                                       
      FOREIGN KEY (topping_id) REFERENCES TOPPING(topping_id)                                                                                                                                                                       
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- COMMENT                                                                                                                                                                                                                        
  CREATE TABLE `COMMENT` (                                                                                                                                                                                                          
    comment_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                      
    user_id INT NOT NULL,                                                                                                                                                                                                           
    product_id INT NOT NULL,                                                                                                                                                                                                        
    order_detail_id INT NOT NULL,                                                                                                                                                                                                   
    rating INT NOT NULL,                                                                                                                                                                                                            
    comment TEXT NOT NULL,                                                                                                                                                                                                          
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                                                                                                                                                                                 
    CONSTRAINT fk_comment_user                                                                                                                                                                                                      
      FOREIGN KEY (user_id) REFERENCES `USER`(user_id),                                                                                                                                                                             
    CONSTRAINT fk_comment_product                                                                                                                                                                                                   
      FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id),                                                                                                                                                                      
    CONSTRAINT fk_comment_order_detail                                                                                                                                                                                              
      FOREIGN KEY (order_detail_id) REFERENCES ORDER_DETAIL(order_detail_id)                                                                                                                                                        
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- STAMP LOG                                                                                                                                                                                                                      
   CREATE TABLE t_stamp (                                                                                                                                                                                                            
    id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                              
    user_id INT NOT NULL,                                                                                                                                                                                                           
    order_id INT NOT NULL,                                                                                                                                                                                                          
    quantity INT NOT NULL,                                                                                                                                                                                                          
    CONSTRAINT fk_stamp_user                                                                                                                                                                                                        
      FOREIGN KEY (user_id) REFERENCES `USER`(user_id),                                                                                                                                                                             
    CONSTRAINT fk_stamp_order                                                                                                                                                                                                       
      FOREIGN KEY (order_id) REFERENCES ORDERS(order_id)                                                                                                                                                                            
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 
  
    -- USER 샘플                                                                                                                                                                                                                      
  INSERT INTO `USER` (id, pw, name, stamp) VALUES                                                                                                                                                                                   
  ('id01', 'pw01', '김피자', 0),                                                                                                                                                                                                   
  ('id02', 'pw02', '박치즈', 5),                                                                                                                                                                                                   
  ('id03', 'pw03', '이페퍼', 10);                                                                                                                                                                                                  
                                                                                                                                                                                                                                    
  -- DOUGH                                                                                                                                                                                                                          
  INSERT INTO DOUGH (name, image, extra_price) VALUES                                                                                                                                                                               
  ('오리지널', 'dough_original.png', 0),                                                                                                                                                                                            
  ('씬 크러스트', 'dough_thin.png', 0),                                                                                                                                                                                             
  ('치즈 크러스트', 'dough_cheese.png', 2000),                                                                                                                                                                                      
  ('고구마 크러스트', 'dough_sweetpotato.png', 2000),                                                                                                                                                                               
  ('치즈 바이트', 'dough_bite.png', 2500);                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- CRUST                                                                                                                                                                                                                          
  INSERT INTO CRUST (name, image, extra_price) VALUES                                                                                                                                                                               
  ('기본 크러스트', 'crust_basic.png', 0),                                                                                                                                                                                          
  ('치즈 크러스트', 'crust_cheese.png', 3000),                                                                                                                                                                                      
  ('고구마 크러스트', 'crust_sweetpotato.png', 3000),                                                                                                                                                                               
  ('갈릭 크러스트', 'crust_garlic.png', 2500),                                                                                                                                                                                      
  ('치즈 바이트', 'crust_bite.png', 3500);                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  -- TOPPING                                                                                                                                                                                                                        
  INSERT INTO TOPPING (name, image, price) VALUES                                                                                                                                                                                   
  ('페퍼로니', 'topping_pepperoni.png', 1200),                                                                                                                                                                                      
  ('베이컨', 'topping_bacon.png', 1300),                                                                                                                                                                                            
  ('버섯', 'topping_mushroom.png', 800),                                                                                                                                                                                            
  ('양파', 'topping_onion.png', 600),                                                                                                                                                                                               
  ('올리브', 'topping_olive.png', 700),                                                                                                                                                                                             
  ('파인애플', 'topping_pineapple.png', 900),                                                                                                                                                                                       
  ('할라피뇨', 'topping_jalapeno.png', 700),                                                                                                                                                                                        
  ('치즈 추가', 'topping_cheese.png', 1500),                                                                                                                                                                                        
  ('감자', 'topping_potato.png', 900),                                                                                                                                                                                              
  ('불고기', 'topping_bulgogi.png', 1500),                                                                                                                                                                                          
  ('피망', 'topping_pepper.png', 700),                                                                                                                                                                                              
  ('옥수수', 'topping_corn.png', 600);                                                                                                                                                                                              
                                                                                                                                                                                                                                    
  -- PRODUCT                                                                                                                                                                                                                        
  INSERT INTO PRODUCT (name, description, image, base_price) VALUES                                                                                                                                                                 
  ('포테이토 피자', '담백한 감자 토핑이 듬뿍 올라간 피자', 'potato_pizza.jpg', 18900),                                                                                                                                                  
  ('불고기 피자', '달콤한 불고기와 야채의 조합', 'bulgogi_pizza.jpg', 19900),                                                                                                                                                       
  ('페퍼로니 피자', '클래식한 페퍼로니 피자', 'pepperoni_pizza.jpg', 17900),                                                                                                                                                        
  ('콤비네이션 피자', '다양한 토핑의 조화', 'combination_pizza.jpg', 18900),
  ('커스텀 피자', '나만의 개성있는 피자', 'custom_pizza.jpg', 10000);
                                                                                                                                                                                                                                    
  -- PRODUCT_DEFAULT_TOPPING (제품별 기본 토핑)                                                                                                                                                                                     
  -- 감자 피자                                                                                                                                                                                                                      
  INSERT INTO PRODUCT_DEFAULT_TOPPING (product_id, topping_id) VALUES                                                                                                                                                               
  (1, 8),  -- 치즈 추가                                                                                                                                                                                                             
  (1, 9),  -- 감자                                                                                                                                                                                                                  
  (1, 4),  -- 양파                                                                                                                                                                                                                  
  (1, 3);  -- 버섯                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    
  -- 불고기 피자                                                                                                                                                                                                                    
  INSERT INTO PRODUCT_DEFAULT_TOPPING (product_id, topping_id) VALUES                                                                                                                                                               
  (2, 10), -- 불고기                                                                                                                                                                                                                
  (2, 4),  -- 양파
  (2, 8),
  (2, 11), -- 피망                                                                                                                                                                                                                  
  (2, 12); -- 옥수수                                                                                                                                                                                                                
                                                                                                                                                                                                                                    
  -- 페퍼로니 피자                                                                                                                                                                                                                 
  INSERT INTO PRODUCT_DEFAULT_TOPPING (product_id, topping_id) VALUES
  (3, 1),
  (3, 8),  -- 치즈 추가
  (3, 4);  -- 양파

  -- 콤비네이션 피자
  INSERT INTO PRODUCT_DEFAULT_TOPPING (product_id, topping_id) VALUES
  (4, 1),  -- 페퍼로니
  (4, 2),  -- 베이컨
  (4, 3),  -- 버섯
  (4, 4),  -- 양파
  (4, 5),  -- 올리브
  (4, 8),
  (4, 11); -- 피망
  
  CREATE TABLE ADMIN (                                                                                                                                                                                                              
    admin_id INT AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                        
    id VARCHAR(50) NOT NULL UNIQUE,                                                                                                                                                                                                 
    pw VARCHAR(255) NOT NULL,                                                                                                                                                                                                       
    name VARCHAR(50) NOT NULL                                                                                                                                                                                                       
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;                                                                                                                                                                                          
                                                                                                                                                                                                                                    
  INSERT INTO ADMIN (id, pw, name) VALUES                                                                                                                                                                                           
  ('admin', '1234', '관리자');
  
    INSERT INTO TOPPING (name, image, price) VALUES                                                                                                                                                                                   
  ('치킨', 'topping_chicken.png', 1400),                                                                                                                                                                                            
  ('새우', 'topping_shrimp.png', 1500),                                                                                                                                                                                             
  ('불닭', 'topping_fire_chicken.png', 1600),                                                                                                                                                                                       
  ('소시지', 'topping_sausage.png', 1200),                                                                                                                                                                                          
  ('햄', 'topping_ham.png', 1100),                                                                                                                                                                                                  
  ('시금치', 'topping_spinach.png', 700),                                                                                                                                                                                           
  ('브로콜리', 'topping_broccoli.png', 800),                                                                                                                                                                                        
  ('토마토', 'topping_tomato.png', 700),                                                                                                                                                                                            
  ('마늘', 'topping_garlic.png', 600),                                                                                                                                                                                              
  ('고구마', 'topping_sweetpotato.png', 900),                                                                                                                                                                                       
  ('파프리카', 'topping_paprika.png', 800),                                                                                                                                                                                         
  ('콘치즈', 'topping_corn_cheese.png', 1300),                                                                                                                                                                                      
  ('바질', 'topping_basil.png', 600),                                                                                                                                                                                               
  ('루꼴라', 'topping_rucola.png', 900),                                                                                                                                                                                            
  ('양송이', 'topping_button_mushroom.png', 800),                                                                                                                                                                                   
  ('올리브 그린', 'topping_green_olive.png', 700),                                                                                                                                                                                  
  ('스위트콘', 'topping_sweetcorn.png', 600),                                                                                                                                                                                       
  ('크랩', 'topping_crab.png', 1500),
  ('베이컨 크럼블', 'topping_bacon_crumble.png', 1400),                                                                                                                                                                             
  ('치즈볼', 'topping_cheese_ball.png', 1500);
  
    -- user_id 1~3의 주문 3건 생성                                                                                                                                                                                                    
  INSERT INTO ORDERS (user_id, order_table, status)                                                                                                                                                                                 
  VALUES                                                                                                                                                                                                                            
  (1, 'A-1', 'DONE'),                                                                                                                                                                                                               
  (2, 'B-2', 'DONE'),                                                                                                                                                                                                               
  (3, 'C-3', 'DONE');                                                                                                                                                                                                               
                                                                                                                                                                                                                                    
  SET @o1 = (SELECT order_id FROM ORDERS WHERE user_id=1 ORDER BY order_id DESC LIMIT 1);                                                                                                                                           
  SET @o2 = (SELECT order_id FROM ORDERS WHERE user_id=2 ORDER BY order_id DESC LIMIT 1);                                                                                                                                           
  SET @o3 = (SELECT order_id FROM ORDERS WHERE user_id=3 ORDER BY order_id DESC LIMIT 1);                                                                                                                                           

  -- 각 주문에 상세 4개씩 추가 (총 12개)                                                                                                                                                                                            
  INSERT INTO ORDER_DETAIL (order_id, product_id, dough_id, crust_id, quantity, unit_price) VALUES                                                                                                                                  
  (@o1, 1, 1, 1, 1, 18900),                                                                                                                                                                                                         
  (@o1, 2, 1, 2, 1, 19900),                                                                                                                                                                                                         
  (@o1, 3, 2, 1, 1, 17900),                                                                                                                                                                                                         
  (@o1, 4, 2, 3, 1, 18900),                                                                                                                                                                                                         

  (@o2, 1, 1, 1, 1, 18900),                                                                                                                                                                                                         
  (@o2, 2, 1, 2, 1, 19900),                                                                                                                                                                                                         
  (@o2, 3, 2, 1, 1, 17900),                                                                                                                                                                                                         
  (@o2, 4, 2, 3, 1, 18900),                                                                                                                                                                                                         
                                                                                                                                                                                                                                    
  (@o3, 1, 1, 1, 1, 18900),                                                                                                                                                                                                         
  (@o3, 2, 1, 2, 1, 19900),                                                                                                                                                                                                         
  (@o3, 3, 2, 1, 1, 17900),                                                                                                                                                                                                         
  (@o3, 4, 2, 3, 1, 18900);  

  INSERT INTO `COMMENT` (user_id, product_id, order_detail_id, rating, comment) VALUES                                                                                                                                              
  -- user_id = 1                                                                                                                                                                                                                    
  (1, 1, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 1 AND od.product_id = 1 ORDER BY RAND() LIMIT 1), 5, '치즈 듬뿍이라 만족! 고구마 크러스트랑 조합 최고였어요.'),
  (1, 3, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 1 AND od.product_id = 3 ORDER BY RAND() LIMIT 1), 4, '페퍼로니가 넉넉해서 좋았고 도우도 바삭했어요.'),         
  (1, 2, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 1 AND od.product_id = 2 ORDER BY RAND() LIMIT 1), 5, '불고기 양념이 달달해서 가족이 좋아했어요.'),             
  (1, 4, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 1 AND od.product_id = 4 ORDER BY RAND() LIMIT 1), 3, '무난한 맛! 토핑 더 추가하면 더 맛있을 듯.');             
                                                                                                                                                                                                                                    
  -- user_id = 2                                                                                                                                                                                                                    
  INSERT INTO `COMMENT` (user_id, product_id, order_detail_id, rating, comment) VALUES                                                                                                                                              
  (2, 2, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 2 AND od.product_id = 2 ORDER BY RAND() LIMIT 1), 5, '불고기 피자 완전 취향저격! 재주문 의사 있어요.'),        
  (2, 1, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 2 AND od.product_id = 1 ORDER BY RAND() LIMIT 1), 4, '감자 토핑이 고소하고 부드러워요.'),                      
  (2, 4, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 2 AND od.product_id = 4 ORDER BY RAND() LIMIT 1), 4, '콤비네이션은 실패가 없네요.'),                           
  (2, 3, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 2 AND od.product_id = 3 ORDER BY RAND() LIMIT 1), 5, '짭짤한 페퍼로니 최고!');                                 
                                                                                                                                                                                                                                    
  -- user_id = 3                                                                                                                                                                                                                    
  INSERT INTO `COMMENT` (user_id, product_id, order_detail_id, rating, comment) VALUES                                                                                                                                              
  (3, 4, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 3 AND od.product_id = 4 ORDER BY RAND() LIMIT 1), 5, '토핑 밸런스가 좋아요. 아이들도 잘 먹네요.'),             
  (3, 1, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 3 AND od.product_id = 1 ORDER BY RAND() LIMIT 1), 4, '감자+치즈 조합이 부드럽고 맛있어요.'),                   
  (3, 3, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 3 AND od.product_id = 3 ORDER BY RAND() LIMIT 1), 5, '페퍼로니 양이 많아서 좋았습니다.'),                      
  (3, 2, (SELECT od.order_detail_id FROM ORDER_DETAIL od JOIN ORDERS o ON o.order_id = od.order_id WHERE o.user_id = 3 AND od.product_id = 2 ORDER BY RAND() LIMIT 1), 3, '불고기 맛은 괜찮았는데 조금 달았어요.'); 